# Generated by Django 4.1.5 on 2023-01-21 20:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vulspy', '0004_resultid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_subdomain_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_vul', models.CharField(max_length=127)),
                ('sub_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulspy.subdomain')),
            ],
        ),
        migrations.DeleteModel(
            name='ResultID',
        ),
        migrations.AlterField(
            model_name='scanrequest',
            name='scan_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='scan_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulspy.scanrequest'),
        ),
    ]
