# Generated by Django 4.1.5 on 2023-01-22 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vulspy', '0005_subdomain_vulnerabilities_delete_resultid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerabilities',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scanrequest',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
