# Generated by Django 4.1.5 on 2023-01-24 04:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vulspy', '0008_alter_scanrequest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerabilities',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
