# Generated by Django 4.1.5 on 2023-01-28 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulspy', '0009_vulnerabilities_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerabilities',
            name='date',
        ),
        migrations.RemoveField(
            model_name='vulnerabilities',
            name='sub_domain',
        ),
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_port', models.CharField(max_length=128)),
                ('subdomain_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulspy.subdomain')),
            ],
        ),
        migrations.AddField(
            model_name='vulnerabilities',
            name='port',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='vulspy.ports'),
            preserve_default=False,
        ),
    ]
