version: "3"

services:
  web:
    build: ./main
    command: 
      - /bin/bash
      - -c
      - |
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
        celery -A main worker -l info
    ports:
      - 8000:8000
      
    depends_on:
        rabbitmq:
          condition: service_healthy
    restart: on-failure


  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=kaxem
      - RABBITMQ_DEFAULT_PASS=12345678
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 10s
      timeout: 10s
      retries: 5

   
