# Generated by Django 4.1.5 on 2023-01-19 17:41

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vulspy', '0002_scanrequest_delete_inputdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scanrequest',
            name='scan_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
