# Generated by Django 4.1.5 on 2023-01-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulspy', '0003_scanrequest_date_alter_scanrequest_scan_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
