# Generated by Django 4.1.5 on 2023-01-23 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulspy', '0006_vulnerabilities_date_alter_scanrequest_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerabilities',
            name='date',
        ),
    ]
