# Generated by Django 4.1.5 on 2023-01-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulspy', '0007_remove_vulnerabilities_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
