# Generated by Django 4.1.5 on 2023-01-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulspy', '0010_remove_vulnerabilities_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ports',
            old_name='main_port',
            new_name='port_scanned',
        ),
        migrations.RenameField(
            model_name='ports',
            old_name='subdomain_request',
            new_name='scan_request',
        ),
    ]
